language: go
sudo: false
cache:
  directories:
    - $GOPATH/pkg
    - $GOPATH/bin
install:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  - go mod download
script:
  - golangci-lint run --enable-all -D errcheck -D lll -D dupl -D gochecknoglobals -D gosec --deadline 5m ./...
  - go test -race ./...
go:
  - 1.x
  - tip
env:
  - GO111MODULE=on
matrix:
  fast_finish: true
