language: go
sudo: false
install:
  - go get github.com/alecthomas/gometalinter github.com/golang/dep/cmd/dep
  - gometalinter --install
  - dep ensure -v
  - go install ./...
script:
  - gometalinter --disable errcheck --deadline 10m --vendor --tests ./...
  - go test ./...
go:
  - 1.10.x
  - 1.11.x
  - tip
