
[[constraint]]
  name = "cloud.google.com/go"
  version = "0.34.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go-v2"
  version = "0.7.0"

[[constraint]]
  name = "github.com/hashicorp/go-cleanhttp"
  version = "0.5.0"

[prune]
  go-tests = true
  unused-packages = true
